---
'Common Languages':
  de: Deutsch
  en: English
  es: Español
  fr: Français
  it: Italiano
'Other Languages':
  ar: يبرعلا
  bg: Български
  ca: Català
  cs: Česky
  da: Dansk
  eo: Esperanto
  fa: س راف
  ko: 한국어
  id: Bahasa Indonesia
  he: עברית
  lt: Lietuvių
  hu: Magyar
  ms: Bahasa Melayu
  nl: Nederlands
  ja: 日本語
  'no': Norsk (bokmål)
  pl: Polski
  pt: Português
  ru: Русский
  ro: Română
  sk: Slovenčina
  sl: Slovenščina
  sr: Српски / Srpski
  fi: Suomi
  sv: Svenska
  tr: Türkçe
  uk: Українська
  vi: Tiếng Việt
  vo: Volapük
  war: Winaray
  zh: 中文
