development:
  server: "http://192.168.2.101:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://staging2.kluuu.com:9292/faye"
  secret_token: "1ca35552f8b33e95302a951002a835fc39b6699ab2447f9140d36190fca0c0a7"
  signature_expiration: 3600 # one hour  
staging:
  server: "http://staging2.kluuu.com:9292/faye"
  secret_token: "1ca35552f8b33e95302a951002a835fc39b6699ab2447f9140d36190fca0c0a7"
  signature_expiration: 3600 # one hour
