- url: https://voicerepublic.com/users/re-publica-15
  img: images/sponsored_publishers/republica.png
  name: re:publica 2014/2015
  text: >-
    Europe’s biggest internet and digital conference can be listened
    to on Voice Republic since 2014.

- url: https://voicerepublic.com/users/frankfurter-buchmesse
  img: images/sponsored_publishers/frankfurt.png
  name: Frankfurt Book Fair
  text: >-
    The world’s most important event in the book business publishes
    selected content on Voice Republic.

- url: https://voicerepublic.com/users/hkw-berlin
  img: images/sponsored_publishers/kulturen.png
  name: Haus der Kulturen der Welt
  text: >-
    The international cultural center makes their project “100 Years
    of Now” audible on Voice Republic.

- url: https://voicerepublic.com/users/zentrum-geschichte-des-wissens-eth-universitat-zurich
  img: images/sponsored_publishers/zgw.png
  name: ETH/University of Z&uuml;rich
  text: >-
    The Center “History of Knowledge” regularly streams its events
    live from the Cabaret Voltaire. The colloquia and symposia can
    also be listened to in the archive.

- url: https://voicerepublic.com/users/Morgenstadt
  img: images/sponsored_publishers/frauenhofer.png
  name: Fraunhofer Institute
  text: >-
    Voice Republic accompanies the “Urban Future Conference 2015” and
    gives everyone who is interested the opportunity to listen to the
    talks.

- url: https://voicerepublic.com/users/maxim-gorki-theater
  img: images/sponsored_publishers/gorki.png
  name: Maxim Gorki Theater
  text: >-
    The Maxim Gorki Theater in Berlin is one of the most important
    theaters in the German-speaking area and publishes selected
    discussions, lectures and symposia on Voice Republic.

- url: https://voicerepublic.com/users/leipziger-buchmesse
  img: images/sponsored_publishers/leipziger.jpg
  name: Leipziger Buchmesse
  text: >-
    Every Spring, the literature and media business meets up in
    Leipzig and thousands of book fans hear their favourite authors
    read.

- url: https://voicerepublic.com/users/deutscher-ethikrat
  img: images/sponsored_publishers/deutscher-ethikrat.png
  name: Deutscher Ethikrat
  text: >-

- url: https://voicerepublic.com/users/konrad-adenauer-stitung
  img: images/sponsored_publishers/konrad-adenauer.png
  name: Konrad Adenauer Stiftung
  text: >-

- url: https://voicerepublic.com/users/juedischesmuseumberlin
  img: images/sponsored_publishers/juedisches-museum-berlin.png
  name: J&uuml;disches Museum Berlin
  text: >-

- url: https://voicerepublic.com/users/slush-helsinki
  img: images/sponsored_publishers/slush.png
  name: Slush Con
  text: >-

- url: https://voicerepublic.com/users/nzzpodium-berlin
  img: images/sponsored_publishers/nzz.png
  name: NZZ Podium Berlin
  text: >-