durations: [ 30, 45, 60, 90, 120, 240 ]
rtmp:
  discussions: "rtmp://kluuu.com/discussions"
  recordings: "rtmp://kluuu.com/recordings"
errbit:
  api_key: '710bf38280e0f96f26a74682519794d5'
localeapp:
  enabled: true
  api_key: '5EzAUJzfRXXHzt5xW5h6hyOIuJ4dy49d9Il3imi4JKZoXV8IlL'
devise:
  from_address: "noreply@kluuu.com"
  secret_key: '077e0e804b07d4284d6960b23579ca07b7a83bdf65f5c1a21d8d256e3d0ddfaec82bc294bf91e44bb0cc604757141f6b175d7290469fb881e4d347082f7e6481'
  omniauth:
    facebook:
      - '343355799056546'
      - 'ceb280bc9f085cc4b64252f9b75f9895'
      - scope: email
        display: popup
    google_oauth2:
      - '833767655435.apps.googleusercontent.com'
      - 'Qa1tDkIJNp7jwGeSSF7mUG6R'
      - access_type: "offline"
        approval_prompt: ""
rspec:
  gc_cycle: 20
