# this cannot go in settings.yml since fog's providers will
# check for allowed parameters
fog:
  storage:
    provider: Local
    local_root: public/system/cloud
    endpoint: http://localhost:3000/system/cloud
talk_upload_bucket: vr-audio-uploads-dev

# provider: AWS
aws:
  aws_access_key_id: AKIAIGKSA6ESEFZV4DQA
  aws_secret_access_key: 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
